In [8]:
import numpy as np
my_list=[1,2,3]
my_list

[1, 2, 3]

In [9]:
np.array(my_list)

array([1, 2, 3])

In [10]:
my_matrix=[[1,2,3,],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [11]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [14]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [15]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [16]:
np.ones(3)

array([1., 1., 1.])

In [17]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [19]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [21]:
np.linspace(0,5,21)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  , 2.25, 2.5 ,
       2.75, 3.  , 3.25, 3.5 , 3.75, 4.  , 4.25, 4.5 , 4.75, 5.  ])

In [22]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [24]:
np.random.rand(2)

array([0.26469888, 0.56981651])

In [25]:
np.random.rand(5,5)

array([[0.0133355 , 0.74731207, 0.3031862 , 0.82419016, 0.99576682],
       [0.96589889, 0.22776687, 0.16053843, 0.84188096, 0.53333828],
       [0.1555836 , 0.22522745, 0.30532966, 0.64338009, 0.12924973],
       [0.70936916, 0.24639856, 0.78637343, 0.3326789 , 0.59831391],
       [0.01579575, 0.92397372, 0.53619759, 0.7627272 , 0.34837182]])

In [26]:
np.random.randn(5)

array([ 1.71692803, -0.1817757 , -0.69326567,  0.36112296,  0.63791432])

In [27]:
np.random.randn(5,5)

array([[-0.55086287, -0.63360302, -1.20576896, -1.38747658,  0.01447318],
       [ 1.11492375, -0.2372227 , -0.41019638, -1.55410242,  0.76689425],
       [ 1.79801261,  0.50134327, -0.54437983,  0.40362568,  1.02395776],
       [-0.30457818, -0.17264036,  0.92715775,  0.57620534, -0.65103243],
       [-1.0351502 , -0.06244492, -0.53544275, -0.74130453,  0.44179914]])

In [28]:
np.random.randint(0,100)

26

In [29]:
np.random.randint(1,100,10)

array([ 4, 80,  8, 59, 25, 50, 79, 77, 57, 94], dtype=int32)

In [31]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [33]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [34]:
arr=np.arange(25)
ranarr=np.random.randint(0,50,10)

In [35]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [36]:
ranarr

array([38, 18, 22, 10, 10, 23, 35, 39, 23,  2], dtype=int32)

In [37]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [38]:
ranarr

array([38, 18, 22, 10, 10, 23, 35, 39, 23,  2], dtype=int32)

In [39]:
ranarr.max()

np.int32(39)

In [40]:
ranarr.argmax()

np.int64(7)

In [41]:
ranarr.min()

np.int32(2)

In [42]:
ranarr.argmin()

np.int64(9)

In [43]:
arr.shape

(25,)

In [44]:
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [45]:
arr.reshape(1,25).shape

(1, 25)

In [46]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [47]:
arr.reshape(25,1).shape

(25, 1)

In [48]:
arr.dtype

dtype('int64')

In [49]:
arr2=np.array([1.2,5.7,7.4])
arr2.dtype

dtype('float64')

In [51]:
arr=np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [53]:
arr[8]

np.int64(8)

In [54]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [55]:
arr[0:5]=100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [56]:
arr=np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [58]:
slice_of_arr=arr[0:6]
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [59]:
slice_of_arr[:]=99
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [60]:
arr[-1]

np.int64(10)

In [61]:
arr_copy=arr.copy()
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [62]:
arr_2d=np.array(([5,10,15],[20,25,30],[35,40,45]))
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [63]:
arr_2d[1]

array([20, 25, 30])

In [64]:
arr_2d[2][1]

np.int64(40)

In [65]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [68]:
arr_2d[2,1:]

array([40, 45])

In [69]:
arr=np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [71]:
bool_arr=arr>4
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True])

In [72]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [73]:
arr[arr>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
import numpy as np
arr = np.arange(1,10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
arr + arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [8]:
arr * arr

array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])

In [9]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0])

In [10]:
arr/arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [11]:
1/arr

array([1.        , 0.5       , 0.33333333, 0.25      , 0.2       ,
       0.16666667, 0.14285714, 0.125     , 0.11111111])

In [12]:
arr**3

array([  1,   8,  27,  64, 125, 216, 343, 512, 729])

In [13]:
np.sqrt(arr)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        ])

In [14]:
np.exp(arr)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03])

In [15]:
np.sin(arr)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [16]:
np.log(arr)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [17]:
arr.sum()

np.int64(45)

In [18]:
arr.mean()

np.float64(5.0)

In [19]:
arr.max()

np.int64(9)

In [20]:
arr.min()

np.int64(1)

In [21]:
arr.var()

np.float64(6.666666666666667)

In [23]:
arr.std()

np.float64(2.581988897471611)

## Использование горизонтальной и вертикальной осей (Axis)
При работе с двумерными массивами - матрицами - мы работаем со строками (rows) и колонками (columns). Это станет очень важным, когда мы далее будем работать с pandas. В терминах массивов, ось 0 (ноль) это вертикальная ось (строки), а ось 1 это горизонтальная ось (колонки). Эти значения (0,1) следуют в том же порядке, в котором значения перечислены в атрибуте <tt>arr.shape</tt>.

Давайте посмотрим, как можно вычислить агрегатные статистики (sum, min, max и т.д.) с использованием осей.

In [24]:
arr_2d = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr_2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [25]:
arr_2d.sum(axis=0)

array([15, 18, 21, 24])

In [26]:
arr_2d.shape

(3, 4)

In [27]:
arr_2d.sum(axis=1)

array([10, 26, 42])